name: shorts
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */4 * * *" # every 4 hours
  # push:
  #   branches: [master]

env:
  YT_UPLOADER_API: ${{secrets.YT_UPLOADER_API}}

jobs:
  main:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: FedericoCarboni/setup-ffmpeg@v2
      - run: |
          node generate_remotion_data.js
          cd remotion && npm i && npm run build

      - run: ffmpeg -i outputs/shorts.mp4 -af "volume=5.0" -c:v copy outputs/shorts_boosted.mp4

      - run: npm i
      - run: node upload_shorts.cjs
